import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import "./global.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Toaster position="top-right" />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
